### PR TITLE
Added new chat icon

### PR DESCRIPTION
**Pull request by NFSS10**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/8 |
| Decisions | Added new icon to be used in `order-detail`, in robin. |
| Image | imagem |

### CODE REVIEW

**Comment by gcandal** [comment]
@NFSS10 `npm run pretty` for SVG minification.

**Comment by NFSS10** [comment]
> @NFSS10 `npm run pretty` for SVG minification.

@gcandal I ran before pushing, but it didn't do anything

**Comment by gcandal** [comment]
It seems that for some reason we don't have svgo in this repo. Please add it @NFSS10 and check if it's missing in any other repo (storybook, robin, etc)

**Comment by NFSS10** [comment]
> It seems that for some reason we don't have svgo in this repo. Please add it @NFSS10 and check if it's missing in any other repo (storybook, robin, etc)

@gcandal Is it needed in storybook?

**Comment by gcandal** [comment]
> > It seems that for some reason we don't have svgo in this repo. Please add it @NFSS10 and check if it's missing in any other repo (storybook, robin, etc)
> 
> @gcandal Is it needed in storybook?

No, it's not.

**Comment by joamag** [comment]
the extra directory is going to be used

**Comment by joamag** [comment]
@NFSS10 renamed as chat-baloons

**Pull request merged**
