### PR TITLE
Tabs: Visibility toggling via tab options

### PR DESCRIPTION
**Pull request by 3rdvision**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/pull/355#issuecomment-1092583546 |
| Decisions | - Add visibility toggling via tab options. |

### CODE REVIEW

**Review by BeeMargarida — COMMENTED** [review]
If `android:windowSoftInputMode="adjustResize"` is to be used, this solution will need to be adapted to hide the tabs when the keyboard opens

**Comment by 3rdvision** [comment]
> If `android:windowSoftInputMode="adjustResize"` is to be used, this solution will need to be adapted to hide the tabs when the keyboard opens

This solution provides a way to hide the keyboard by adding the option `hiddenTabBar` to the screen. Just like we're doing [here](https://github.com/ripe-tech/ripe-robin-revamp/blob/master/routes/tab-stack.js#L108) in `screenOptions` to hide the header. And the idea, if it's not clear, was to use this option to toggle the tab visibility but that would be done in robin and not here.

I think I can instead add a prop to `hideOnKeyboard` that when true uses the event of the keyboard to maintain a keyboardVisible state and hide/show.

**Comment by BeeMargarida** [comment]
> I think I can instead add a prop to `hideOnKeyboard` that when true uses the event of the keyboard to maintain a keyboardVisible state and hide/show.

Yes, I was talking about this. Since that logic would need to be added to Robin in that place you mentioned, or here. I think it would make more sense here with the prop.

**Review by BeeMargarida — COMMENTED** [review]
In iOS it works 👌 but in Android there is still flickering and the Tabs update totally, you can see the blue line moving to the middle. Is there any way of hiding the bar instead of removing and re-rendering it again?

| - | - |
| --- | --- |
| iOS | Android |
| https://user-images.githubusercontent.com/25725586/163962513-aba1c9b7-30e9-454b-9ee2-9c2a8543f43d.MP4 |  https://user-images.githubusercontent.com/25725586/163970587-bbb4c060-c679-4c4c-8152-d86e1e4aacc5.mp4 |

**Review by joamag — APPROVED** [review]

**Pull request merged**
