### PR TITLE
ContainerDraggable swipe capabilities

### PR DESCRIPTION
**Pull request by NFSS10**
| - | - |
| --- | --- |
| Issue | - |
| Dependencies |  https://github.com/ripe-tech/ripe-components-react-native/pull/97 |
| Decisions | Added swipe capabilities to `ContainerSwipeable` component  |
| Animated GIF | RN-ContainerSwipeable_swipe_relative <br>**Also working with fullscreen:**<br>RN-ContainerSwipeable_swipe_fullscreen<br>**With **`doFullscreenSnap`** equal to **`true`**:**<br>RN-ContainerSwipeable_doFullscreenSnap |

### CODE REVIEW

**Comment by gcandal** [comment]
@NFSS10 please merge against `ns/container-swipeable_fix`

**Comment by gcandal** [comment]
@NFSS10 please apply the UX tweaks we discussed

**Comment by joamag** [comment]
@gcandal please extract this behavior into an external component

**Comment by gcandal** [comment]
@joamag I've moved the old implementation to `containerOpenable` with nearly no changes (just added new props to manipulate the header) and extracted the new behavior to `containerDraggable`.

**Pull request merged**
