### PR TITLE
feat: lightbox component tunes

### PR DESCRIPTION
**Pull request by beneditomauro**
| - | - |
| --- | --- |
| Decisions | Use uri instead of url, anf move the lightbox component to the `molecules` folder |
| Animated GIF | Before <br> HIRnSrKaX1 <br>  After <br>  NTHh8eANRa|

### CODE REVIEW

**Comment by gcandal** [comment]
Are you saying that I can't use `lightbox` with a URL with get params?

**Comment by beneditomauro** [comment]
You're right, it appear to be a "bug" in the story

**Comment by beneditomauro** [comment]
@gcandal This will just happen in storybook, the supposed solution (https://github.com/storybookjs/storybook/tree/v4.0.0-alpha.8/addons/knobs#withknobs-vs-withknobsoptions) `escapeHTML: true` is crashing the whole app, don't know if it's worth the trouble, maybe wontfix this PR ?

**Comment by gcandal** [comment]
Yep let's just close this.

**Pull request closed without merging**
